# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux/Qt5', 'FreeBSD/Qt5', 'Android/Qt5', 'Windows/Qt5']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/kirigami': '@stable'
    'frameworks/ki18n': '@stable'
    'frameworks/kcontacts': '@stable'
    'frameworks/kcoreaddons': '@stable'
    'frameworks/knotifications': '@stable'
    'frameworks/prison': '@stable'

- 'on': ['Linux/Qt5', 'FreeBSD/Qt5']
  'require':
    'frameworks/kservice': '@stable'
    'frameworks/kio': '@stable'
    'frameworks/purpose': '@stable'

- 'on': ['Linux/Qt5']
  'require':
    'frameworks/networkmanager-qt': '@stable'

- 'on': ['Linux/Qt6', 'FreeBSD/Qt6', 'Android/Qt6', 'Windows/Qt6']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/kirigami': '@latest-kf6'
    'frameworks/ki18n': '@latest-kf6'
    'frameworks/kcontacts': '@latest-kf6'
    'frameworks/kcoreaddons': '@latest-kf6'
    'frameworks/knotifications': '@latest-kf6'
    'frameworks/prison': '@latest-kf6'

- 'on': ['Linux/Qt6', 'FreeBSD/Qt6']
  'require':
    'frameworks/kservice': '@latest-kf6'
    'frameworks/kio': '@latest-kf6'
    'frameworks/purpose': '@latest-kf6'

- 'on': ['Linux/Qt6']
  'require':
    'frameworks/networkmanager-qt': '@latest-kf6'

Options:
  require-passing-tests-on: [ 'Linux', 'FreeBSD' ]
