# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
 - 'on': ['Linux', 'FreeBSD', 'Android', 'Windows']
   'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/kirigami': '@latest-kf6'
    'frameworks/ki18n': '@latest-kf6'
    'frameworks/kcontacts': '@latest-kf6'
    'frameworks/kcoreaddons': '@latest-kf6'
    'frameworks/knotifications': '@latest-kf6'
    'frameworks/prison': '@latest-kf6'

 - 'on': ['Linux', 'FreeBSD']
   'require':
    'frameworks/kservice': '@latest-kf6'
    'frameworks/kio': '@latest-kf6'
    'frameworks/kcrash': '@latest-kf6'

 - 'on': ['Linux']
   'require':
    'frameworks/networkmanager-qt': '@latest-kf6'

Options:
 require-passing-tests-on: ['Linux', 'FreeBSD']
