# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/kirigami': '@stable'
    'frameworks/ki18n': '@stable'
    'frameworks/kcontacts': '@stable'
    'frameworks/kcoreaddons': '@stable'
    'frameworks/knotifications': '@stable'
    'frameworks/prison': '@stable'

- 'on': ['Linux', 'FreeBSD']
  'require':
    'frameworks/kservice': '@stable'
    'frameworks/kio': '@stable'
    'frameworks/purpose': '@stable'

- 'on': ['Linux']
  'require':
    'frameworks/networkmanager-qt': '@stable'
